"""add grade to user

Revision ID: 11e9e3423ba2
Revises: 5149d0388d
Create Date: 2015-08-09 18:33:51.819111

"""

# revision identifiers, used by Alembic.
revision = '11e9e3423ba2'
down_revision = '5149d0388d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('grade', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'grade')
    ### end Alembic commands ###
