"""add is_display to user

Revision ID: 5149d0388d
Revises: 432b80af4cb6
Create Date: 2015-08-08 17:27:43.881046

"""

# revision identifiers, used by Alembic.
revision = '5149d0388d'
down_revision = '432b80af4cb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_display', sa.Boolean(), server_default=sa.text(u'true'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_display')
    ### end Alembic commands ###
