"""add ordinal to problem

Revision ID: 51f6cea2cd3e
Revises: 53047d3c6fda
Create Date: 2015-08-08 15:14:31.792177

"""

# revision identifiers, used by Alembic.
revision = '51f6cea2cd3e'
down_revision = '53047d3c6fda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('ordinal', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'ordinal')
    ### end Alembic commands ###
