"""init

Revision ID: 53047d3c6fda
Revises: None
Create Date: 2015-07-27 22:34:59.639939

"""

# revision identifiers, used by Alembic.
revision = '53047d3c6fda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=64)),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_date_created'), 'category', ['date_created'], unique=False)
    op.create_table('oj_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('oj_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('accept', sa.Integer(), server_default=u'0', nullable=True),
    sa.Column('submit', sa.Integer(), server_default=u'0', nullable=True),
    sa.Column('rating', sa.Integer(), server_default=u'0', nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oj_account_date_created'), 'oj_account', ['date_created'], unique=False)
    op.create_index(op.f('ix_oj_account_oj_name'), 'oj_account', ['oj_name'], unique=False)
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oj_name', sa.String(length=64), nullable=False),
    sa.Column('problem_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_date_created'), 'problem', ['date_created'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), server_default=sa.text(u'false'), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_problem_date_created'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_oj_account_oj_name'), table_name='oj_account')
    op.drop_index(op.f('ix_oj_account_date_created'), table_name='oj_account')
    op.drop_table('oj_account')
    op.drop_index(op.f('ix_category_date_created'), table_name='category')
    op.drop_table('category')
    ### end Alembic commands ###
