"""add ordinal to category

Revision ID: 56d33d6c723f
Revises: 51f6cea2cd3e
Create Date: 2015-08-08 15:43:41.637499

"""

# revision identifiers, used by Alembic.
revision = '56d33d6c723f'
down_revision = '51f6cea2cd3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('ordinal', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'ordinal')
    ### end Alembic commands ###
